codecov:
  require_ci_to_pass: true

coverage:
  precision: 2
  round: down
  range: "40...100"

  status:
    project:
      default:
        target: 40%
        threshold: 5%
        informational: false
    patch:
      default:
        target: 60%
        threshold: 10%
        informational: false

parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      method: false
      macro: false

comment:
  layout: "reach,diff,flags,files"
  behavior: default
  require_changes: false
  require_base: false
  require_head: true

ignore:
  - "tests/**/*"
  - "**/__init__.py"
